### ISSUE TITLE
There seems to be a problem at the NCBI server. The retrieved annotation is not valid XML. Try again later

### ISSUE THREAD

**Issue by mcurto** [kaspermunch/sap#13]
Hi,
I am trying to classify multiple 12S sequences with the GenBank database. The program ran for the first one but the in the second I am getting this error message:

"There seems to be a problem at the NCBI server. The retrieved annotation is not valid XML. Try again later"

I am using the following command:
 sap --project Ave_04-11-2020 -x 90 -e macurto@fc.ul.pt MiFish_04-11-2020_OTUSeqs.fasta

Is that an internet problem? Should I just wait and restart later?

Thank you in advance for your help.

**Comment by kaspermunch** [comment]
Did the analysis complete when you redid a bit later?

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 23 Feb 2022, 20.24 +0100, mcurto ***@***.***>, wrote:

Hi,
I am trying to classify multiple 12S sequences with the GenBank database. The program ran for the first one but the in the second I am getting this error message:

"There seems to be a problem at the NCBI server. The retrieved annotation is not valid XML. Try again later"

I am using the following command:
sap --project Ave_04-11-2020 -x 90 -e ***@***.******@***.***> MiFish_04-11-2020_OTUSeqs.fasta

Is that an internet problem? Should I just wait and restart later?

Thank you in advance for your help.

**Comment by mcurto** [comment]
Hi,
I has not. I also did a test where I ran each sequence individually and out of the 143 sequences the program ran completely for 104. For example the following sequence I get a result for OTU_0 but I get an error for OTU_1. When I do a blast  in GenBank with OTU_1 I see there are some matches with sequences from ENA. Do you think this might be the problem?
Thanks for your help,
Manuel

>OTU_0
CACCGCGGTTATACGAGAGGCTCAAGTTGATAAACCCCGGCGTAAAGAGT
GGTTAAGGAAGATTAAAAACTAAAGCCGAATGCTTTCAAAGCTGTTATAC
GCTTCCGAGAGTAAGAAGATCAACTACGAAAGTGACTTTATAGCCCCTGA
CCCCACGAAAGCTATGGCA
>OTU_1
CACCGCGGTTAGACGAGAGGCCCTAGTTGATATTATAACGGCGTAAAGGG
TGGTTAAGGATAAATAATAATAAAGCCAAATGGCCCCTTGGCCGTCATAC
GCTTCTAGGTGTCCGAAGCCCCATATACGAAAGTAGCTTTAATTAACCCA
CCTGACCCCACGAAAACTGAGAAA

**Comment by kaspermunch** [comment]
Hi Manuel,

I have made a Docker image of SAP that has not yet made it to the downloads page. It has some updates that should fix your problem and allows SAP to be run painlessly on machine. You need to install Docker on your machine: https://www.docker.com/products/docker-desktop

If you are on Mac or linux you can then run sap like this:

docker run --rm -v $PWD:/code/sap kaspermunch/sap:latest

On windows it should run like this (not tested):

docker run --rm -v %CD%:/code/sap kaspermunch/sap:latest


Where it is not possible to install Docker, as is often the case on shared computing facilities, the image can be pulled using Singularity https://sylabs.io/singularity (you only need to do this once):

singularity pull sap docker://kaspermunch/sap:latest

Then just run the created image as any other executable:

        ./sap [ARGUMENTS]

Let me know if it works for you.

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 28 Feb 2022, 22.13 +0100, mcurto ***@***.***>, wrote:

Hi,
I has not. I also did a test where I ran each sequence individually and out of the 143 sequences the program ran completely for 104. For example the following sequence I get a result for OTU_0 but I get an error for OTU_1. When I do a blast in GenBank with OTU_1 I see there are some matches with sequences from ENA. Do you think this might be the problem?
Thanks for your help,
Manuel

OTU_0
CACCGCGGTTATACGAGAGGCTCAAGTTGATAAACCCCGGCGTAAAGAGT
GGTTAAGGAAGATTAAAAACTAAAGCCGAATGCTTTCAAAGCTGTTATAC
GCTTCCGAGAGTAAGAAGATCAACTACGAAAGTGACTTTATAGCCCCTGA
CCCCACGAAAGCTATGGCA
OTU_1
CACCGCGGTTAGACGAGAGGCCCTAGTTGATATTATAACGGCGTAAAGGG
TGGTTAAGGATAAATAATAATAAAGCCAAATGGCCCCTTGGCCGTCATAC
GCTTCTAGGTGTCCGAAGCCCCATATACGAAAGTAGCTTTAATTAACCCA
CCTGACCCCACGAAAACTGAGAAA

**Comment by mcurto** [comment]
Thanks Kasper. I tried but I am having the same problem with the same sequences.
Best,
Manuel

**Comment by kaspermunch** [comment]
The problem was a non-ascii character in taxonomy XML from NCBIi. I changed the string encoding to utf-8. That fixed it. I updated the docker image, so the docker run command should pull the new version.
