### ISSUE TITLE
Sequence stuck at "Using cached Blast results... done"

### ISSUE THREAD

**Issue by ekrell** [kaspermunch/sap#4]
I am using SAP with a custom database that has SAP-formatted headers. 

The first run went very well. I used the default options other than the path to local Fasta. 
Was surprised that I got results in just a couple days, even though I was using > 2000 sequences. 
It took quite a while for the initial database setup, but thats fine since I expected that would only need to be done one. 

Then, I wanted to run again with '-x 50'.
I was concerned when I saw that it said "Building native SAP database...".
So I went to investigate the ".sapdb" directory that gets made. Inside, I saw that the copy of the fasta was being modified, as the size increased whenever I ran 'ls -l'. 
Since SAP takes a while anyway (with as many sequences as I use), its not terrible to wait for this each time. But I believe it should be able to detect that it does not need to. 
More critically, this means I don't think I can run multiple SAP jobs at once with the same custom database or else will be writing over each other. This is a big deal for me since I have plenty of jobs planned and plenty of cores for doing so. 

But, the main issue is this: A sequence got stuck for over a week. 
It said "Using cached Blast results... done." And then printed a block of numbers (taxids? gis?). 
And it repeating doing so with the exact same block of numbers, seemingly infinite. 
When I used ctrl-c to abort the SAP job, it gave up on that sequence and went to the next. 
Obviously I can't be manually checking the job for these things. 
Here is what I am talking about:

```
Using cached Blast results... done.
1040334108(l!?) 1040334094(l!?) 1040334080(l!?) 1040334066(l!?)                                                           1040334052(l!?) 1040334038(l!?) 1040334024(l!?)
1040334010(l!?) 1040333996(l!?) 1040333982(l!?)
1040333968(l!?) 1040333954(l!?) 1040333940(l!?)
1040333926(l!?) 1040333912(l!?) 1040333898(l!?)
1036141163(l!?) 1036141149(l!?) 1036141133(l!?)
1036141119(l!?) 1036141105(l!?) 1036141091(l!?)
1036141077(l!?) 1036141063(l!?) 1036141035(l!?) 
1036141021(l!?) 1035522283(l!?) 1034467235(l!?)
1034467221(l!?) 1034467207(l!?) 1034467193(l!?)
1034467179(l!?) 1034467151(l!?) 1034467137(l!?)
1034467123(l!?) 1034467109(l!?) 1034467095(l!?)
1033205984(l!?) 1033205970(l!?) 1033205956(l!?)
1033205942(l!?) 1033205928(l!?) 1033205914(l!?)
1033205900(l!?) 1033205886(l!?) 1033205872(l!?)
1033205858(l!?) 1033205844(l!?) 1033205830(l!?)
1031620983(l!?) 1031620969(l!?) 1031620955(l!?)
1031620941(l!?) 1027946642(l!?) 1027946628(l!?)
.....
1025813587(l!?) 1025813573(l!?) 1025813559(l!?)
1025813545(l!?) 1025813531(l!?) 1025813517(l!?)
1025813503(l!?) 1025813489(l!?) 1025813475(l!?)
1025813461(l!?) 1025813447(l!?) 1025813433(l!?)
1025813419(l!?) 1025813405(l!?) 1025813391(l!?)
1025813377(l!?)  
Using cached Blast results... done.
1040334108(l!?) 1040334094(l!?) 1040334080(l!?) 1040334066(l!?)                                                           1040334052(l!?) 1040334038(l!?) 1040334024(l!?)
1040334010(l!?) 1040333996(l!?) 1040333982(l!?)
1040333968(l!?) 1040333954(l!?) 1040333940(l!?)
1040333926(l!?) 1040333912(l!?) 1040333898(l!?)
1036141163(l!?) 1036141149(l!?) 1036141133(l!?)
1036141119(l!?) 1036141105(l!?) 1036141091(l!?)
1036141077(l!?) 1036141063(l!?) 1036141035(l!?) 
1036141021(l!?) 1035522283(l!?) 1034467235(l!?)
1034467221(l!?) 1034467207(l!?) 1034467193(l!?)
1034467179(l!?) 1034467151(l!?) 1034467137(l!?)
1034467123(l!?) 1034467109(l!?) 1034467095(l!?)
1033205984(l!?) 1033205970(l!?) 1033205956(l!?)
1033205942(l!?) 1033205928(l!?) 1033205914(l!?)
1033205900(l!?) 1033205886(l!?) 1033205872(l!?)
1033205858(l!?) 1033205844(l!?) 1033205830(l!?)
1031620983(l!?) 1031620969(l!?) 1031620955(l!?)
1031620941(l!?) 1027946642(l!?) 1027946628(l!?)
.....
1025813587(l!?) 1025813573(l!?) 1025813559(l!?)
1025813545(l!?) 1025813531(l!?) 1025813517(l!?)
1025813503(l!?) 1025813489(l!?) 1025813475(l!?)
1025813461(l!?) 1025813447(l!?) 1025813433(l!?)
1025813419(l!?) 1025813405(l!?) 1025813391(l!?)
1025813377(l!?)  
```

It seemed to be okay, but now I see something else interesting:

```
Searching database (excluding Actinopterygii environmental sample, Alepes melanoptera, Alepes vari, Carangidae sp. NPPF1116, Carangidae sp. NPPF1136, Carangoides equula, Cubiceps gracilis, Decapterus macarellus, Holocentridae sp. BBOLD_AAE4293, Ictalurus lupus, Sargocentron coruscum, Selar boops, Selar crumenophthalmus, Selaroides leptolepis, Trachurus capensis, Trachurus trachurus)... System call "makeblastdb -dbtype nucl -title /media/Wapuilani/evan/repo/SAP_formatter_clean/Simons_x50/tmpBlastDB.fasta -in /media/Wapuilani/evan/repo/SAP_formatter_clean/Simons_x50/tmpBlastDB.fasta" return code 1                                                                                                                
done.
```                                                                 

I feel like all of this is related to using a local database, but the first time I did so it worked very well.

**Comment by kaspermunch** [comment]
That sounds strange. I am on vacation now, and will not have time to look at it until August. Let me know if it is still relevant by then: kaspermunch@birc.au.dk

**Comment by kaspermunch** [comment]
Hi Evan,

Sorry about the delayed response. Hope it is still relevant. I’ll have a look at the excessive local database building. About the sequence getting stuck: If you are on Windows, I think that is a known issue that has to do with the maximum allowed length fo paths. If you remove the limitation on file name length it probably solves then problem.

Kasper
