### ISSUE TITLE
SAP NCBI server error

### ISSUE THREAD

**Issue by lyy005** [kaspermunch/sap#8]
Dear Kasper,
Thank you for updating the conda installation of SAP. It's super easy to install now. 

I ran into an error when running SAP: 
"There seems to be a problem at the NCBI server. The retrieved annotation is not valid XML. Try again later."

The command I use is: 
sap Ac12S_ASV_fasta.fa.2.fas -d Ac12S_ASV_fasta.fa.2 -e yli19@nd.edu

Thank you for any suggestions! 

YY

**Comment by kaspermunch** [comment]
Fixed by removing the clade level from taxonomies.
