### ISSUE TITLE
gxx_linux-64 needed

### ISSUE THREAD

**Issue by TristanLefebure** [kaspermunch/sap#9]
Hello
The gxx_linux-64 conda package seems necessary for SAP to be compiled.

Without:
```
(sap) [tristan@asellus sap] python setup.py install
[...]
/opt/src/miniconda2/envs/sap/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/src/miniconda2/envs/sap/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/src/miniconda2/envs/sap/include -fPIC -Iext/barcoder -I/opt/src/miniconda2/envs/sap/include/python2.7 -c ext/barcoder/mcmc.cpp -o build/temp.linux-x86_64-2.7/ext/barcoder/mcmc.o
x86_64-conda_cos6-linux-gnu-cc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command '/opt/src/miniconda2/envs/sap/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
```

The following solves the problem: 
`conda install -n sap gxx_linux-64`

Best

--Tristan

**Comment by kaspermunch** [comment]
Hi Tristan,

Thanks for the heads up. I will add it to the documentation.

Cheers,
Kasper
On 12 May 2020, 11.55 +0200, Tristan Lefebure <notifications@github.com>, wrote:

Hello
The gxx_linux-64 conda package seems necessary for SAP to be compiled.

Without:

(sap) [tristan@asellus sap] python setup.py install
[...]
/opt/src/miniconda2/envs/sap/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/src/miniconda2/envs/sap/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/src/miniconda2/envs/sap/include -fPIC -Iext/barcoder -I/opt/src/miniconda2/envs/sap/include/python2.7 -c ext/barcoder/mcmc.cpp -o build/temp.linux-x86_64-2.7/ext/barcoder/mcmc.o
x86_64-conda_cos6-linux-gnu-cc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command '/opt/src/miniconda2/envs/sap/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1


The following solves the problem:
conda install -n sap gxx_linux-64

Best

--Tristan
